# EODHD API
eodhd_api_key = "66b0a456553244.60099335"
# Reddit API
[reddit]
client_id = "W7LL_6Zyf_4q8fRpzVDEwA"
client_secret = "aUf5rZm4mE8UlSjv76XnnYNIvRbwDg"
user_agent = "FinancialSentimentBot/1.0"