# EODHD API
eodhd_api_key = "66b0a456553244.60099335"
# Reddit API
[reddit]
client_id = "W7LL_6Zyf_4q8fRpzVDEwA"
client_secret = "aUf5rZm4mE8UlSjv76XnnYNIvRbwDg"
user_agent = "FinancialSentimentBot/1.0"
[x]
api_key = "BwAMpPxh7TrXB2VCpLWEXqBkf"
api_secret = "WAtx7d31tdn0RHypPUj1NUH5eaqqkNZGDYVWwVjL7mpHPWvAxa"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAC2UzAEAAAAAqk4RivJ1gksmtkXORE2HNhKpE%2FY%3DGNodTEOK7Pwg2H18MrT45ZEZrwZNU8E0JyyYU14ltvNFuqhTo8"
access_token = "1889658175185362944-IMDtqZQe9joEwIhhRlQwAtMqAMt0yA"
access_token_secret = "UXVrDY7CXdJqoqMEid247Q29ZAxaAtXaPulsiHJ2zfjGH"